INSERT INTO DEPARTMENT (NAME) values ('department1');
INSERT INTO DEPARTMENT (NAME) values ('department2');


INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny1', 1 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny2', 1 ,1 , '0912345678', 'us', 33, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny3', 1 ,1 , '0912345678', 'japan', 34, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny4', 1 ,1 , '0912345678', 'china', 35, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny5', 1 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny6', 1 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny7', 1 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny8', 1 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny9', 2 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny10', 2 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO EMPLOYEE (NAME, DEPARTMENT_ID, GENDER, PHONE_NUMBER,ADDRESS,AGE, CREATE_TIME, UPDATE_TIME) values ('Sunny11', 2 ,1 , '0912345678', 'taiwan', 32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
